import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {migrate} from 'wesa';
import {difference,includes,without} from 'lodash-es';
import {selectedEngines,revision} from '../src/storage/revisions/local/20260907050000_keep_selected_engines.js';
const read=p=>fs.readFileSync(p,'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
const allRevisions=JSON.parse(read('src/storage/config.json')).revisions.local;
const revisions=allRevisions.slice(0,allRevisions.indexOf(revision)+1);
function migrations(state){
 const calls=[];
 const browser={storage:{local:{get:async keys=>keys===null?structuredClone(state):Object.fromEntries((Array.isArray(keys)?keys:[keys]).filter(k=>k in state).map(k=>[k,structuredClone(state[k])])),set:async v=>Object.assign(state,plain(v)),remove:async keys=>(Array.isArray(keys)?keys:[keys]).forEach(k=>delete state[k])}}};
 return {calls,context:{getAvailableRevisions:async()=>revisions,getCurrentRevision:async()=>state.storageVersion,getRevision:async({revision:id})=>{calls.push(id);const c=vm.createContext({browser,Date,targetEnv:'chrome',isMobile:async()=>false,isAndroid:async()=>false,getDayPrecisionEpoch:v=>Math.floor(v/86400000)*86400000});vm.runInContext(read(`src/storage/revisions/local/${id}.js`).replace(/^import .*;\n/gm,'').replace(/export \{[^}]+\};/,'this.result={upgrade,revision,message};'),c);return c.result;}}};
}
test('fresh installation executes the entire migration history and ends with exactly 17 selected engines',async()=>{const state={};const {context,calls}=migrations(state);await migrate(context,{silent:true,data:{install:true,update:false}});assert.equal(calls.length,revisions.length);assert.deepEqual(state.engines,selectedEngines);assert.deepEqual(state.disabledEngines,[]);assert.equal(state.storageVersion,revision);assert.ok(state.searchModeAction);});
test('v5 upgrade preserves capture/browse preferences, and later startup does not reset user choices',async()=>{const state={storageVersion:revisions.at(-2),engines:['baidu','bing'],disabledEngines:['bing'],searchModeAction:'capture',searchModeContextMenu:'browse',appTheme:'dark'};const {context,calls}=migrations(state);await migrate(context,{silent:true});assert.deepEqual(state.engines,selectedEngines);assert.equal(state.searchModeAction,'capture');assert.equal(state.searchModeContextMenu,'browse');assert.equal(state.appTheme,'dark');state.disabledEngines=['bing'];state.engines.reverse();const before=structuredClone(state);await migrate(context,{silent:true});assert.deepEqual(state,before);assert.equal(calls.length,1);});
function harness(){const options={engines:[...selectedEngines],disabledEngines:[],searchModeAction:'capture',bypassImageHostBlocking:true};const c=vm.createContext({difference,includes,without,browser:{runtime:{getURL:p=>'https://test.invalid'+p}},storage:{get:async()=>structuredClone(options)}});vm.runInContext(read('src/utils/data.js').replace(/export \{[\s\S]*?\};/,''),c);vm.runInContext(read('src/utils/app.js').replace(/^import[\s\S]*?from '[^']+';\n/gm,'').replace(/export \{[\s\S]*?\};/,''),c);return {c,options};}
test('17-site capture/browse routing covers PNG JPEG WebP GIF AVIF, repeated use and each individual selection',async()=>{const {c,options}=harness();for(const mode of ['capture','browse'])for(const type of ['image/png','image/jpeg','image/webp','image/gif','image/avif'])for(let round=0;round<2;round++){options.searchModeAction=mode;const s=await c.createSession({engine:'allEngines',sessionType:'search',sessionOrigin:'action'});const tasks=await c.getSearches({imageType:type,imageDataUrl:`data:${type};base64,`},s.engines,mode);assert.deepEqual(plain(tasks.map(t=>t.engine)),selectedEngines);assert.ok(tasks.every(t=>t.assetType==='image'&&t.sendsReceipt));assert.equal(tasks.filter(t=>t.isExec).length,16);assert.equal(tasks.find(t=>t.engine==='pinterest').isTaskId,true);}for(const id of selectedEngines){options.disabledEngines=[id];assert.equal((await c.createSession({engine:'allEngines'})).engines.includes(id),false);assert.deepEqual(plain((await c.createSession({engine:id})).engines),[id]);}});
test('all five entry modes respect the 17-site selection, with URL limited to real URL-capable engines',async()=>{const {c}=harness();for(const mode of ['selectUrl','selectImage','capture','browse','url']){const image=mode==='url'?{imageType:'image/png',imageUrl:'https://test.invalid/sample.png'}:{imageType:'image/png',imageUrl:'https://test.invalid/sample.png',imageDataUrl:'data:image/png;base64,'};const supported=await c.getSupportedEngines(image,selectedEngines,mode);assert.deepEqual(plain(supported),mode==='url'?['googleLens','bing','yandex']:selectedEngines);}});
